// ---------------------------------------------------------------------------
// The person modal — add or edit a sign-in.
//
// Two people use this portal: the owner and the bookkeeper. This is the one
// form for both, opened from Admin → People:
//
//   Add a person     name, username, role, a password (generated by default)
//   click a name     name, role, "Set a new password", "Change username", Delete
//
// Everything that lives in auth — the username, the password, the role's
// server-side guard, deletion — runs through netlify/functions/admin-users.js,
// because those need the service-role key and that key can never be in a
// browser. The one profile column written directly is full_name, under RLS.
//
// Nothing here knows about clients: nobody signs in as a client, and the
// system sends no email, so there is no welcome to compose. The result the
// caller gets back carries the one thing that must be shown once and cannot
// be looked up again — the password, with the username it goes with.
// ---------------------------------------------------------------------------

import { supabase, errorMessage } from './client.js';
import { formModal } from './ui.js';
import {
  callAdminUsers, passwordFields, usernameOf, MIN_PASSWORD, USERNAME_RE,
} from './accounts.js';

// Bookkeeper first so a select left untouched lands on the lesser role.
export const ROLE_OPTIONS = [
  { value: 'staff', label: 'Bookkeeper' },
  { value: 'owner', label: 'Owner' },
];

/** The role as a person would say it. */
export function roleLabel(role) {
  if (role === 'owner') return 'Owner';
  if (role === 'staff') return 'Bookkeeper';
  return 'No access';
}

/**
 * A username as typed, made into one the function will accept: trimmed and
 * lower-cased. Null when it is not a username at all — the same rule the
 * server applies, so the form can say so before a round trip is spent.
 */
export function normalizeUsername(raw) {
  const value = String(raw == null ? '' : raw).trim().toLowerCase();
  return USERNAME_RE.test(value) ? value : null;
}

const USERNAME_RULE = 'Lower-case letters and digits, 2 to 31 characters; dots, '
  + 'dashes and underscores are fine inside. This is what they type to sign in.';

/**
 * Open it.
 *
 *   person   the profile being edited ({ id, email, full_name, role }), or
 *            null to create one
 *   selfId   the signed-in profile's id, so nobody demotes or deletes
 *            themselves from inside the browser
 *
 * Resolves null if it was cancelled, otherwise { handoff, editing, deleted }:
 *
 *   handoff  { username, password } when a password was assigned here, and the
 *            caller's to display once. Null otherwise.
 *   editing  whether an existing account was edited rather than created.
 *   deleted  the account was destroyed; nothing else in the result applies.
 */
export async function openPersonForm({ person = null, selfId = null } = {}) {
  const editing = Boolean(person);
  // Losing your own owner rights is a one-way door from inside the browser:
  // only the other owner (or SQL) can undo it. The server refuses it too.
  const isSelf = editing && person.id === selfId;
  const currentUsername = editing ? usernameOf(person.email) : '';

  let handoff = null;
  let deleted = false;

  // An account that was never invited sits on 'none'. The select has to be
  // able to show that honestly, but never to choose it: the option is offered
  // only while it is the truth, and saving with it still selected is refused.
  const roleOptions = editing && person.role === 'none'
    ? [{ value: 'none', label: 'No access (not set up)' }, ...ROLE_OPTIONS]
    : ROLE_OPTIONS;

  const result = await formModal({
    title: editing
      ? (person.full_name || currentUsername || 'Edit person')
      : 'Add a person',
    submitLabel: editing ? 'Save person' : 'Create sign-in',
    intro: editing
      ? 'Everything here applies the moment you save. Devices they are '
        + 'already signed in on stay signed in.'
      : 'This creates the sign-in and sets its password straight away. Hand '
        + 'them the username and password yourself — nothing is emailed.',
    fields: [
      {
        name: 'full_name',
        label: 'Full name',
        type: 'text',
        required: true,
        value: editing ? person.full_name || '' : '',
        placeholder: 'Dana Whitfield',
        autocomplete: 'off',
      },
      {
        name: 'username',
        label: editing ? 'Change username' : 'Username',
        type: 'text',
        required: true,
        value: currentUsername,
        placeholder: 'dana',
        autocomplete: 'off',
        autocapitalize: 'none',
        autocorrect: 'off',
        spellcheck: 'false',
        hint: editing
          ? `Currently "${currentUsername}". ${USERNAME_RULE}`
          : USERNAME_RULE,
      },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        value: editing ? person.role : 'staff',
        options: roleOptions,
        disabled: isSelf,
        hint: isSelf
          ? 'Another owner has to change your own role.'
          : 'The owner manages sign-ins and the business details. The '
            + 'bookkeeper does everything else.',
      },
      ...passwordFields({ optional: editing }),
    ],
    onSubmit: async (values) => {
      const username = normalizeUsername(values.username);
      if (!username) throw new Error(`That is not a username. ${USERNAME_RULE}`);

      const role = isSelf ? person.role : values.role;
      if (role !== 'owner' && role !== 'staff') {
        throw new Error('Pick a role — Owner or Bookkeeper.');
      }

      if (!editing) {
        await callAdminUsers({
          action: 'create',
          username,
          full_name: values.full_name,
          role,
          password: values.password,
        });
        handoff = { username, password: values.password };
        return;
      }

      // Check the optional password before touching anything, so a typo here
      // cannot leave the edit half-applied.
      if (values.password && values.password.length < MIN_PASSWORD) {
        throw new Error(`A new password needs at least ${MIN_PASSWORD} characters.`);
      }

      // The profile column first: it is the one write that runs under RLS
      // rather than through the function, and the cheapest to retry.
      if (values.full_name !== (person.full_name || '')) {
        const { error } = await supabase
          .from('profiles')
          .update({ full_name: values.full_name })
          .eq('id', person.id);
        if (error) throw new Error(errorMessage(error));
      }

      if (username !== currentUsername.toLowerCase()) {
        await callAdminUsers({ action: 'set-username', user_id: person.id, username });
      }

      if (!isSelf && role !== person.role) {
        await callAdminUsers({ action: 'set-role', user_id: person.id, role });
      }

      if (values.password) {
        await callAdminUsers({ action: 'set-password', user_id: person.id, password: values.password });
        handoff = { username, password: values.password };
      }
    },

    // Deleting a sign-in. Offered only when editing an account that is not
    // your own — you cannot delete yourself, and the server refuses it too
    // (admin-users), because a browser check is a convenience, not a boundary.
    onDelete: editing && !isSelf
      ? async () => {
        await callAdminUsers({ action: 'delete', user_id: person.id });
        deleted = true;
      }
      : null,
    deleteLabel: 'Delete sign-in',
    // Built only when there is somebody to delete: this object is an
    // argument, so its template literal runs when the call is made, not when
    // the delete button is pressed, and `person.full_name` on a null person
    // would throw before the Add form ever opened.
    confirmDelete: editing ? {
      title: `Delete ${person.full_name || currentUsername || 'this sign-in'}?`,
      body: [
        'They lose their sign-in immediately, on every device.',
        'Everything they recorded stays — invoices, payments, expenses, notes '
          + '— but their name comes off it. This cannot be undone.',
      ],
    } : undefined,
  });

  if (!result) return null;
  if (result === 'deleted' || deleted) return { deleted: true, editing, handoff: null };

  return { handoff, editing, deleted: false };
}
